/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistema_almacen_depsa;

import javax.swing.JOptionPane;

/**
 *
 * @author NESTOR
 */
public class PanelClientes extends javax.swing.JPanel {

    /**
     * Creates new form PanelClientes
     */
    public PanelClientes() {
        initComponents();
        // === CONFIGURACIÓN DE LA TABLA CLIENTES ===
        // === CONFIGURACIÓN DE LA TABLA CLIENTES ===
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();

        modelo.addColumn("Tipo de Documento");
        modelo.addColumn("N° Documento");
        modelo.addColumn("Nombre(s)");
        modelo.addColumn("Ap. Paterno");
        modelo.addColumn("Ap. Materno");
        modelo.addColumn("Dirección");
        modelo.addColumn("Teléfono");

        tablaClientes.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtTipoDoc = new javax.swing.JTextField();
        txtDocumento = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtApePaterno = new javax.swing.JTextField();
        txtApeMaterno = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("GESTIÓN DE CLIENTES");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Tipo de Documento:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Numero de Documento:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Nombre(s):");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Apellido Paterno:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Apellido Materno:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Direccion:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Telefono:");

        txtDocumento.addActionListener(this::txtDocumentoActionPerformed);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setText("GUARDAR CLIENTE");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo de Documento", "Numero de Documento", "Nombre(s)", "Apellido Paterno", "Apellido Materno", "Dirección", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(tablaClientes);

        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton2.setText("EDITAR");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(this::jButton3ActionPerformed);

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton4.setText("LIMPIAR");
        jButton4.addActionListener(this::jButton4ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtApePaterno, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(txtApeMaterno)
                                    .addComponent(txtDireccion)
                                    .addComponent(txtTelefono)
                                    .addComponent(txtDocumento)
                                    .addComponent(txtNombres)
                                    .addComponent(txtTipoDoc)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jButton3)
                                .addGap(282, 282, 282)
                                .addComponent(jButton4)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(612, 612, 612))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1407, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTipoDoc))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApePaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApeMaterno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // 1. Extraemos lo que el usuario escribió (para poder analizarlo)
        String tipoDoc = txtTipoDoc.getText();
        String documento = txtDocumento.getText();
        String nombres = txtNombres.getText();
        String apePaterno = txtApePaterno.getText();
        String apeMaterno = txtApeMaterno.getText();
        String direccion = txtDireccion.getText();
        String telefono = txtTelefono.getText();

        // 2. FILTRO BASE: Validamos que no haya ningún campo vacío
        if (tipoDoc.isEmpty() || documento.isEmpty() || nombres.isEmpty()
                || apePaterno.isEmpty() || apeMaterno.isEmpty() || direccion.isEmpty()
                || telefono.isEmpty()) {
            JOptionPane.showMessageDialog(null, "¡Atención! Llena todas las cajas del formulario.");
            return; // Freno 1
        }
        // --- FILTRO DOCUMENTO: Validar DNI (8) o CE (9) ---
        // Convertimos lo que escribió el usuario a mayúsculas para evitar errores (ej. "ce" -> "CE")
        String tipoDocFiltro = tipoDoc.toUpperCase();

        if (tipoDocFiltro.equals("DNI")) {
            if (documento.length() != 8) {
                JOptionPane.showMessageDialog(null, "Error: El DNI debe tener exactamente 8 dígitos.");
                return; // Freno
            }
        } else if (tipoDocFiltro.equals("CE")) {
            if (documento.length() != 9) {
                JOptionPane.showMessageDialog(null, "Error: El Carné de Extranjería (CE) debe tener 9 dígitos.");
                return; // Freno
            }
        } else {
            // Si el usuario escribe "Pasaporte" u otra cosa que tu sistema aún no acepta
            JOptionPane.showMessageDialog(null, "Error: Tipo de documento no válido. Use 'DNI' o 'CE'.");
            return; // Freno
        }

        // 3. FILTRO TELÉFONO A: Exactamente 9 dígitos
        if (telefono.length() != 9) {
            JOptionPane.showMessageDialog(null, "Error: El teléfono debe tener exactamente 9 números.");
            return; // Freno 2
        }

        // 4. FILTRO TELÉFONO B: Solo números (sin letras ni símbolos)
        try {
            Long.parseLong(telefono);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Error: El teléfono no puede contener letras.");
            return; // Freno 3
        }
        
        // ==============================================================================
        // REQ-013: Evitar DNI duplicado
        // ¿Qué hace?: Recorre la tabla visual. Si encuentra que el DNI que el usuario
        //             escribió ya existe en la columna 1, frena todo el proceso.
        // ==============================================================================
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaClientes.getModel();
        
        for (int i = 0; i < modelo.getRowCount(); i++)
        {
            String docExistente = modelo.getValueAt(i, 1).toString();
            
            if (docExistente.equals(documento)) 
            {
                JOptionPane.showMessageDialog(null, "Error: El DNI/CE " + documento + " ya está registrado en el sistema.");
                GestorArchivos.registrarLog("ERROR DUPLICADO", "Intento de registro doble con DNI: " + documento);
                return; // Freno 4: Cancela el guardado
            }
        }

        // 5. ¡TODO PERFECTO! Ahora sí inyectamos los datos como una nueva fila en nuestra tabla
        
        modelo.addRow(new Object[]{tipoDoc, documento, nombres, apePaterno, apeMaterno, direccion, telefono});

        // ==============================================================================  
     // REQ-GA-01:ALMACENAMIENTO DE DATOS (Gestor 1)
        // Le enviamos nuestra tabla visual (tablaClientes) al Gestor de Archivos. 
        // Su trabajo es recorrer toda la tabla y guardar la información actualizada 
        // en el bloc de notas ('clientes.txt') para no perder los datos al cerrar el sistema.
        // ==============================================================================
        GestorArchivos.guardarClientes(tablaClientes);
        
        // ==============================================================================  
     // REQ-GA-02: cargarClientes() - RECUPERACIÓN DE DATOS (Gestor 2)
       // Apenas se dibuja la ventana, mandamos a leer el bloc de notas 
       // para rellenar la tabla y que el usuario vea sus datos anteriores.
       // ==============================================================================
      
    // INTEGRACIÓN REQ-GA-03: Registro de hsitorial ( GESTOR 3)
      // ¿Qué hace?: Llama a la herramienta del Log para anotar de forma oculta en el 
      //             bloc de notas que este vendedor logró guardar un cliente.
      // ¿Por qué usamos la variable 'documento' en vez de 'txtDocumento.getText()'?
      // Porque 'documento' toma el dato seguro que ya está guardado en la memoria de la 
      // computadora, evitando el riesgo de leer la caja visual por si esta se borra o 
      // se queda vacía durante el proceso.
      // ==============================================================================
        GestorArchivos.registrarLog("REGISTRO", "Se guardó el cliente con DNI: " + documento);
        
     
        
        // 6. Limpiamos las cajas (dejándolas vacías) para el siguiente cliente
        txtTipoDoc.setText("");
        txtDocumento.setText("");
        txtNombres.setText("");
        txtApePaterno.setText("");
        txtApeMaterno.setText("");
        txtDireccion.setText(""); 
        txtTelefono.setText("");    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // Vaciamos todas las cajas de texto
        txtTipoDoc.setText("");
        txtDocumento.setText("");
        txtNombres.setText("");
        txtApePaterno.setText("");
        txtApeMaterno.setText("");
        txtDireccion.setText("");
        txtTelefono.setText("");

// Un toque profesional: Mandamos el cursor de vuelta a la primera caja
        txtTipoDoc.requestFocus();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
// 1. Averiguamos qué fila de la tabla seleccionó el usuario (empiezan a contar desde 0)
        int filaSeleccionada = tablaClientes.getSelectedRow();
        // ¿Qué hace?: Le pregunta automáticamente a la tabla en qué fila se hizo clic.
        // ¿Qué devuelve?: Devuelve el número de la POSICIÓN elegida (no la cantidad).
        //   -> Como toda lista en programación, la primera posición empieza en 0.
        //   -> Si el usuario presiona el botón sin seleccionar nada, devuelve -1.

        // 2. Si es mayor o igual a 0, significa que sí seleccionó una fila válida
        if (filaSeleccionada >= 0) 
        {
            
            // 3. Extraemos el DNI de la tabla ANTES de borrarlo (está en la columna 1)
            // Lo necesitamos para mostrarlo en el mensaje y guardarlo en la caja negra.
            String dniEliminado = tablaClientes.getValueAt(filaSeleccionada, 1).toString();
            
            // 4. REQ-015: Confirmación de seguridad
            // Bloquea borrados accidentales preguntando "Sí" o "No"
            int respuesta = JOptionPane.showConfirmDialog(null, 
                    "¿Está seguro de eliminar permanentemente al cliente con DNI " + dniEliminado + "?", 
                    "Confirmar Eliminación", JOptionPane.YES_NO_OPTION);
            
            // Si el usuario presionó "Sí" (YES_OPTION)
            if (respuesta == JOptionPane.YES_OPTION) {
                // Llamamos al modelo de la tabla y borramos esa fila específica de la pantalla
                javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaClientes.getModel();
                modelo.removeRow(filaSeleccionada);
                
                // ==============================================================================
                // REQ-GA: INTEGRACIÓN CON GESTORES DE ARCHIVOS
                // 1. Reescribimos el bloc de notas para que ya no incluya a este cliente.
                // 2. Dejamos el rastro en el Log.
                // ==============================================================================
                GestorArchivos.guardarClientes(tablaClientes);
                GestorArchivos.registrarLog("ELIMINACIÓN", "Se eliminó al cliente con DNI: " + dniEliminado);
                
                JOptionPane.showMessageDialog(null, "Cliente eliminado correctamente.");
            }
            
        } 
        else 
        {
            // Si es -1, significa que no seleccionó nada. Le avisamos (Freno).
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un cliente de la tabla para eliminar.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // 1. Averiguamos qué fila quiere editar el usuario
        int filaSeleccionada = tablaClientes.getSelectedRow();

        // 2. Si seleccionó una fila válida (posición 0, 1, 2, etc.)
        if (filaSeleccionada >= 0) {
            
            // --- INICIO DE VALIDACIONES (Frenos de seguridad) ---
            String tipoDoc = txtTipoDoc.getText();
            String documento = txtDocumento.getText();
            String nombres = txtNombres.getText();
            String apePaterno = txtApePaterno.getText();
            String apeMaterno = txtApeMaterno.getText();
            String direccion = txtDireccion.getText();
            String telefono = txtTelefono.getText();

            // Freno 1: Ningún campo vacío
            if (tipoDoc.isEmpty() || documento.isEmpty() || nombres.isEmpty()
                    || apePaterno.isEmpty() || apeMaterno.isEmpty() || direccion.isEmpty()|| telefono.isEmpty())
            {
                JOptionPane.showMessageDialog(null, "Error: Ningún campo puede quedar vacío al actualizar.");
                return; 
            }

            // Freno 2: Teléfono válido (9 números exactos)
            if (telefono.length() != 9) {
                JOptionPane.showMessageDialog(null, "Error: El teléfono debe tener exactamente 9 números.");
                return; 
            }
            try 
            {
                Long.parseLong(telefono);
            }
            catch (NumberFormatException e)
            {
                JOptionPane.showMessageDialog(null, "Error: El teléfono no puede contener letras.");
                return; 
            }
            // --- FIN DE VALIDACIONES ---

            // Obtenemos el modelo de la tabla
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaClientes.getModel();

            // 3. Sobreescribimos celda por celda usando las variables que ya validamos
            // setValueAt( El nuevo texto , en qué fila , en qué columna )
            modelo.setValueAt(tipoDoc, filaSeleccionada, 0); 
            modelo.setValueAt(documento, filaSeleccionada, 1); 
            modelo.setValueAt(nombres, filaSeleccionada, 2); 
            modelo.setValueAt(apePaterno, filaSeleccionada, 3); 
            modelo.setValueAt(apeMaterno, filaSeleccionada, 4); 
            modelo.setValueAt(direccion, filaSeleccionada, 5); 
            modelo.setValueAt(telefono, filaSeleccionada, 6); 

            // ==============================================================================
            // REQ-GA: INTEGRACIÓN CON GESTORES DE ARCHIVOS
            // Actualizamos el bloc de notas con los datos editados y anotamos en el log.
            // ==============================================================================
            GestorArchivos.guardarClientes(tablaClientes);
            GestorArchivos.registrarLog("ACTUALIZACIÓN", "Se editaron los datos del cliente con DNI/CE: " + documento);

            JOptionPane.showMessageDialog(null, "Cliente actualizado correctamente.");

        } 
        else 
        {
            // Si la posición es -1, mostramos error
            JOptionPane.showMessageDialog(null, "Por favor, seleccione un cliente de la tabla para editar.");
        }
        // ¿Qué hace JOptionPane?: Llama a una ventana emergente (pop-up) visual.
        // ¿Para qué sirve aquí?: Para lanzarle un cuadro de alerta en medio de la pantalla al usuario si comete un error 
        //(como no seleccionar a nadie)
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTextField txtApeMaterno;
    private javax.swing.JTextField txtApePaterno;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoDoc;
    // End of variables declaration//GEN-END:variables
}
