/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package sistema_almacen_depsa;

/**
 *
 * @author NESTOR
 */
public class PanelProductos extends javax.swing.JPanel {

    /**
     * Creates new form PanelProducto
     */
    public PanelProductos() //constructor del panel
    {
        initComponents();

        // === CONFIGURACIÓN DE LA TABLA ===
        // 1. Creamos el "molde" de la tabla
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel();

        // 2. Agregamos las columnas exactas que necesitamos
        modelo.addColumn("Código");
        modelo.addColumn("Nombre");
        modelo.addColumn("Precio");
        modelo.addColumn("Stock");
        modelo.addColumn("Categoría");

        // 3. Le ponemos este molde ya listo a nuestra tabla visual
        tablaProductos.setModel(modelo);
        // Leemos el bloc de notas y dibujamos la tabla al iniciar la pantalla
        GestorArchivos.cargarProductos(tablaProductos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtStock = new javax.swing.JTextField();
        txtCategoria = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        btnEditar = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("GESTIÓN DE PRODUCTOS");

        jButton1.setText("GUARDAR PRODUCTO");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Código:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Precio:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Stock:");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Categoria:");

        txtCodigo.addActionListener(this::txtCodigoActionPerformed);

        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaProductos);

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(this::btnEditarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5))
                                        .addGap(64, 64, 64)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txtStock, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtNombre, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCategoria, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(61, 61, 61))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnEditar)
                        .addGap(385, 385, 385)
                        .addComponent(jButton1)))
                .addGap(443, 443, 443))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnEditar))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// ==============================================================================
        // NIVEL 1 DE SEGURIDAD (EL PORTERO VISUAL)
        // ==============================================================================
        // Verificamos con un IF que el usuario no haya dejado ninguna cajita en blanco
        if (txtCodigo.getText().isEmpty() || txtNombre.getText().isEmpty()
                || txtPrecio.getText().isEmpty() || txtStock.getText().isEmpty() || txtCategoria.getText().isEmpty())
        {
            // Si hay algo vacío, sacamos una alerta en pantalla y detenemos todo con el "return"
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, llene todos los campos antes de guardar.", "Error de Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // ==============================================================================
        // INICIO DEL PROCESO DE GUARDADO O ACTUALIZACIÓN
        // ==============================================================================
        try 
        {
            // --- PASO 1: CAPTURA DE DATOS ---
            // Extraemos el texto exacto que el usuario escribió en la interfaz
            String codigo = txtCodigo.getText();
            String nombre = txtNombre.getText();
            String categoria = txtCategoria.getText();

            // Convertimos los textos de Precio y Stock a verdaderos números (Double e Integer)
            double precio = Double.parseDouble(txtPrecio.getText());
            int stock = Integer.parseInt(txtStock.getText());

            // --- PASO 2: CREACIÓN Y FILTRO (EL ESCUDO INTERNO) ---
            // Enviamos los datos a la clase Producto. Aquí se activan las validaciones (REQ-003, 004).
            // Si el precio o stock son negativos, el código frena en seco aquí y salta al 'catch'.
            Producto nuevoProducto = new Producto(codigo, nombre, precio, stock, categoria);

            // --- PASO 3: LÓGICA INTELIGENTE (¿NUEVO O EDICIÓN?) ---
            // Conectamos con el 'molde' de la tabla para manipular las filas
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaProductos.getModel();
            
            // NUEVO: Preguntamos si el usuario seleccionó una fila previamente con el botón "Editar"
            int filaSeleccionada = tablaProductos.getSelectedRow();

            if (filaSeleccionada >= 0)
            {
                // ---> MODO ACTUALIZAR <---
                // Si hay una fila seleccionada, la sobreescribimos usando los datos del objeto blindado.
                // Así evitamos que el producto se duplique.
                modelo.setValueAt(nuevoProducto.getCodigo(), filaSeleccionada, 0);
                modelo.setValueAt(nuevoProducto.getNombre(), filaSeleccionada, 1);
                modelo.setValueAt(nuevoProducto.getPrecio(), filaSeleccionada, 2);
                modelo.setValueAt(nuevoProducto.getStock(), filaSeleccionada, 3);
                modelo.setValueAt(nuevoProducto.getCategoria(), filaSeleccionada, 4);

                tablaProductos.clearSelection(); // Quitamos la marca azul de selección
                
                GestorArchivos.registrarLog("ACTUALIZACIÓN PRODUCTO", "Se actualizó el producto: " + nombre);
                javax.swing.JOptionPane.showMessageDialog(this, "¡Producto actualizado correctamente!");
                
            } 
            else
            {
                // ---> MODO NUEVO <---
                // Si no hay ninguna fila seleccionada, inyectamos una fila nueva al final de la tabla.
                modelo.addRow(new Object[]{
                    nuevoProducto.getCodigo(),
                    nuevoProducto.getNombre(),
                    nuevoProducto.getPrecio(),
                    nuevoProducto.getStock(),
                    nuevoProducto.getCategoria()
                });
                
                GestorArchivos.registrarLog("REGISTRO PRODUCTO", "Se registró el producto: " + nombre);
                javax.swing.JOptionPane.showMessageDialog(this, "¡Producto registrado en el inventario exitosamente!");
            }

            // --- PASO 4: PERSISTENCIA EN EL DISCO DURO (LA PIZARRA Y EL DIARIO) ---
            // Borramos el archivo .txt viejo y guardamos la tabla entera actualizada (REQ-001)
            GestorArchivos.guardarProductos(tablaProductos);

            // --- PASO 5: LIMPIEZA DE INTERFAZ ---
            // Vaciamos las cajitas de texto dejándolas listas para el siguiente ingreso
            txtCodigo.setText("");
            txtNombre.setText("");
            txtPrecio.setText("");
            txtStock.setText("");
            txtCategoria.setText("");

        } 
        // ==============================================================================
        // NIVEL 2 DE SEGURIDAD (ATRAPA-ERRORES)
        // ==============================================================================
        catch (NumberFormatException e) 
        {
            // Salta si el usuario intentó romper el sistema escribiendo letras en vez de números (ej. "veinte")
            javax.swing.JOptionPane.showMessageDialog(this, "Error: El Precio y el Stock deben ser números válidos.", "Dato Incorrecto", javax.swing.JOptionPane.ERROR_MESSAGE);
        } 
        catch (IllegalArgumentException e) 
        {
            // Salta si la clase Producto detectó una regla de negocio rota (ej. precio negativo)
            // e.getMessage() imprime exactamente el texto del error que programaste en tu clase Producto
            javax.swing.JOptionPane.showMessageDialog(this, e.getMessage(), "Alerta de Seguridad", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        // ==============================================================================
        // REQ-004 (Parte 1): PREPARACIÓN PARA ACTUALIZAR (Efecto Editar)
        // ¿Qué hace?: Verifica que se haya seleccionado un producto y sube sus datos 
        //             a las cajas de texto para poder modificar el stock (u otro dato).
        // ==============================================================================
        
        // 1. Averiguamos qué fila seleccionó el usuario en la tabla visual
        int filaSeleccionada = tablaProductos.getSelectedRow();

        // 2. Si el resultado es -1, significa que no hizo clic en ninguna fila
        if (filaSeleccionada == -1) {
            // Le mostramos un mensaje de alerta y detenemos el proceso con el 'return'
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, seleccione un producto de la tabla para editar.", 
                    "Aviso", javax.swing.JOptionPane.WARNING_MESSAGE);
            return; 
        }

        // 3. VIAJE DE DATOS: Extraemos el texto de cada columna de la fila seleccionada
        //    y lo enviamos a sus respectivas cajitas blancas.
        txtCodigo.setText(tablaProductos.getValueAt(filaSeleccionada, 0).toString());
        txtNombre.setText(tablaProductos.getValueAt(filaSeleccionada, 1).toString());
        txtPrecio.setText(tablaProductos.getValueAt(filaSeleccionada, 2).toString());
        txtStock.setText(tablaProductos.getValueAt(filaSeleccionada, 3).toString());
        txtCategoria.setText(tablaProductos.getValueAt(filaSeleccionada, 4).toString());
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtCategoria;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables
}
